### ISSUE TITLE
搜索后返回数据为空

### ISSUE THREAD

**Issue by ISuuuu** [Justin3go/SearchSearchGo#16]
### 需求描述
阿里云服务器中 使用docker 配置了 es 和ssgo。 搜索后 返回空数据：
```
{
    "took": 2,
    "total": 0,
    "data": []
}
``` 
IP: 
http://IP/api/search?query=hello&pageNo=1&pageSize=10
可能与我的es 创建的索引aliyunpan有关 
参数如下:
```
PUT /aliyunpan
{
  "settings": {
    "index": {
      "number_of_shards": 3,  
      "number_of_replicas": 2
    }
  }
}
``` 
 
![image](https://github.com/Justin3go/SearchSearchGo/assets/16700132/70fc75a8-f1e6-4e7b-998f-8ef56284e649)

**Comment by Justin3go** [comment]
索引名可以通过环境变量`ES_INDEX`配置

ES里面有数据吗？试试：
```shell
curl -XGET 'http://localhost:9200/<你的索引名>/_count'
```

**Comment by ISuuuu** [comment]
```
{"count":0,"_shards":{"total":3,"successful":3,"skipped":0,"failed":0}}  
``` 
es版本：7.6.2

**Comment by Justin3go** [comment]
> ```
> {"count":0,"_shards":{"total":3,"successful":3,"skipped":0,"failed":0}}  
> ```
> 
> es版本：7.6.2

那应该是你的ElasticSearch里面本身就没数据
