### ISSUE TITLE
只能阿里云盘吗，能添加夸克吗

### ISSUE THREAD

**Issue by im-dashan** [Justin3go/SearchSearchGo#17]
### 自检清单

> 请仔细检查下方列表，将你已经完成的动作前方`[]`填入`[x]`

- [] 确认仓库中Issues中没有相似的问题
- [] 确认仓库中Discussions中也没有相似的讨论
- [] 包含截图/视频演示描述，除非你认为文字已经能表达清楚

### 需求描述

> 在这里描述你的需求

### 在线演示

> 可选，这在里详细演示你的需求，如果有在线链接、现成可参考的demo这对于笔者来说将更加清楚地理解你的需求

### 补充说明

> 没说完？在这里继续~

**Comment by Justin3go** [comment]
目前只抓取了阿里云盘的资源，暂无计划抓取其他网盘的资源
